- name: Creates all droplets
  digital_ocean: >
    state=present
    client_id={{ do_client_id }}
    api_key={{ do_api_key }}
    id={{ item.id }}
    name={{ item.name }}
    size_id={{ item.size_id }}
    region_id={{ item.region_id }}
    image_id={{ item.image_id }}
    ssh_key_ids={{ item.ssh_key_id }}
    wait_timeout=600
  with_items: boxes
  register: new_droplet
- debug: >
    msg="Droplet {{ item.droplet.name }} has ID={{ item.droplet.id }} and IP={{ item.droplet.ip_address }}"
  with_items: new_droplet.results
- name: Ensure new Droplets IP is not in known hosts
  shell: 'ssh-keygen -f "$HOME/.ssh/known_hosts" -R {{ item.droplet.ip_address }}'
  with_items: new_droplet.results
- name: Adding new Droplet to hosts
  add_host: name={{ item.droplet.ip_address }} groups=newdroplet
  with_items: new_droplet.results
