- name: ensure apt cache is up to date
  action: apt update_cache=yes

- name: ensure packages are installed
  action: apt name={{item}}
  with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

- name: ensure database is created
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{dbname}}

- name: ensure user has access to database
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- name: ensure user does not have unnecessary privilege
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- stat: path=/etc/profile.d/rvm.sh
  register: rvm_folder
